export const strings = {
  // Welcome & Onboarding
  welcome: {
    title: "欢迎使用 Paseo",
    subtitle: "连接您的电脑即可开始使用",
    scanQR: "扫描二维码",
    directConnection: "直接连接",
    pasteLink: "粘贴配对链接",
    settings: "设置",
  },

  // Pair Link Modal
  pairLink: {
    title: "粘贴配对链接",
    helper: "从您的服务器粘贴配对链接。",
    label: "配对链接",
    placeholder: "https://app.paseo.sh/#offer=...",
    cancel: "取消",
    pairing: "配对中...",
    pair: "配对",
    failed: "配对失败",
    pasteError: "请粘贴配对链接（.../#offer=...）",
    missingOffer: "链接必须包含 #offer=...",
    invalidLink: "无效的配对链接",
    unableToPair: "无法配对主机",
  },

  // Add Host Modal
  addHost: {
    title: "直接连接",
    helper: "输入 Paseo 服务器的地址。",
    hostLabel: "主机",
    portLabel: "端口",
    hostPlaceholder: "localhost",
    portPlaceholder: "6767",
    useSSL: "使用 SSL",
    passwordLabel: "密码",
    passwordPlaceholder: "可选",
    advanced: "高级",
    uriPlaceholder: "tcp://localhost:6767?ssl=true",
    cancel: "取消",
    connecting: "连接中...",
    connect: "连接",
    failed: "连接失败",
    showPassword: "显示密码",
    hidePassword: "隐藏密码",
    showAdvanced: "显示高级选项",
    hideAdvanced: "隐藏高级选项",
    hostRequired: "主机为必填项",
    portRange: "端口必须在 1 到 65535 之间",
    invalidConnection: "无效的连接",
    connectionFailed: `无法连接到 \${endpoint}。`,
    incorrectPassword: "密码错误",
    passwordRequired: "需要密码",
    timeout: "连接超时。请检查主机/端口和您的网络。",
    refused: "连接被拒绝。服务器是否在此地址运行？",
    notFound: "找不到主机。请检查主机名并重试。",
    unreachable: "主机不可达。请检查您的网络和防火墙。",
    tlsError: "TLS 错误。直接连接仅在守护进程前面有 TLS 终结器时才使用 SSL。",
    genericError: "无法连接。请检查主机/端口以及守护进程是否可达。",
  },

  // Add Host Method Modal
  addHostMethod: {
    title: "添加连接",
    directConnection: "直接连接",
    directConnectionDesc: "局域网或 VPN。",
    scanQR: "扫描二维码",
    scanQRDesc: "加密中继连接。",
    pasteLink: "粘贴配对链接",
    pasteLinkDesc: "加密中继连接。",
  },

  // Settings Screen
  settings: {
    title: "设置",
    general: "通用",
    appearance: "外观",
    shortcuts: "快捷键",
    integrations: "集成",
    permissions: "权限",
    diagnostics: "诊断",
    about: "关于",
    connections: "连接",
    orchestration: "编排",
    providers: "提供商",
    daemon: "守护进程",
    projects: "项目",
    app: "应用",
    host: "主机",
    back: "返回",
    local: "本地",
    switchHost: "切换主机",
    addHost: "添加主机",
    defaultSend: "默认发送",
    defaultSendHint: "代理运行时按回车键的行为",
    interrupt: "中断",
    queue: "排队",
    serviceURLs: "服务 URL",
    serviceURLsHint: "从运行脚本打开 URL 的位置",
    ask: "询问",
    inPaseo: "在 Paseo 中",
    externalBrowser: "外部浏览器",
    terminalScrollback: "终端回滚",
    terminalScrollbackHint: "内置终端缓冲区保留的行数",
    testAudio: "测试音频",
    playing: "播放中...",
    playTest: "播放测试",
    appVersion: "应用版本",
    thisDevice: "此设备",
    offline: "离线",
    versionDiff: "版本与此设备不同",
    releaseChannel: "发布渠道",
    releaseChannelHint: "切换到 Beta 可以更早获得更新并帮助改进",
    stable: "稳定版",
    beta: "测试版",
    appUpdates: "应用更新",
    readyToInstall: `准备安装: \${version}`,
    checking: "检查中...",
    check: "检查",
    installing: "安装中...",
    updateTo: `更新到 \${version}`,
    update: "更新",
    installDesktopUpdate: "安装桌面更新",
    installDesktopUpdateMsg: "将更新此电脑上的 Paseo",
    installUpdate: "安装更新",
    cancel: "取消",
    error: "错误",
    unableToUpdate: "无法打开更新确认对话框。",
    connectedHosts: "已连接的主机",
    loadingSettings: "加载设置中...",
    searchHosts: "搜索主机...",
    noHost: "无主机",
  },

  // Host Page
  host: {
    notFound: "未找到主机",
    relay: "中继",
    local: "本地",
    connections: "连接",
    removeConnection: "移除连接",
    removeConfirm: `确定要移除 \${title} 吗？此操作不可撤销。`,
    cancel: "取消",
    remove: "移除",
    timeout: "超时",
    pairDevices: "配对设备",
    pairADevice: "配对设备",
    pairHint: "扫描二维码或复制链接以将手机连接到此主机",
    orchestration: "编排",
    connectToManage: "连接到此主机以管理编排",
    enablePaseoTools: "启用 Paseo 工具",
    enablePaseoToolsHint: "代理将能够管理 worktree、代理和计划",
    systemPrompt: "系统提示",
    systemPromptHint: "为所有代理添加系统提示",
    edit: "编辑",
    appendSystemPrompt: "追加系统提示",
    placeholder: "始终保持回复简洁。",
    reset: "重置",
    saving: "保存中...",
    save: "保存",
    restartDaemon: "重启守护进程",
    restartHint: "重启守护进程。应用将自动重新连接",
    restarting: "重启中...",
    restart: "重启",
    unableToReconnect: "无法重新连接",
    didNotComeBack: `\${host.label} 未恢复在线。请验证它是否已重启。`,
    hostUnavailable: "主机不可用",
    hostUnavailableMsg: "此主机未连接。请等待它上线后再重启。",
    hostOffline: "主机离线",
    hostOfflineMsg: "此主机离线。Paseo 会自动重新连接...",
    failedRestart: "发送重启请求失败。Paseo 会自动重新连接...",
    unableToOpenRestart: "无法打开重启确认对话框。",
    dangerZone: "危险区域",
    removeHost: "移除主机",
    removeHostHint: "从此设备移除此主机及其保存的连接",
    removeHostConfirm: `确定要移除 \${host.label} 吗？这将删除其保存的连接。`,
    unableToRemoveHost: "无法移除主机",
    unableToRemoveConnection: "无法移除连接",
    renameHost: "重命名主机",
    myHost: "我的主机",
    editLabel: "编辑标签",
    rename: "重命名",
  },

  // Providers
  providers: {
    title: "提供商",
    disabled: "已禁用",
    loading: "加载中",
    error: "错误",
    available: "可用",
    notInstalled: "未安装",
    modelCount: `\${count} 个模型`,
    connectToSee: "连接到此主机以查看提供商",
    loadingText: "加载中...",
    addProvider: "添加提供商",
    unableToUpdate: "无法更新提供商",
    addTitle: "添加提供商",
    searchProviders: "搜索提供商",
    noProviders: "未找到提供商",
    cancel: "取消",
    add: "添加",
    adding: "添加中",
    installed: "已安装",
    installInstructions: "安装说明",
    unableToInstall: "无法安装提供商",
    searchModels: "搜索模型",
    addModel: "添加模型",
    diagnostic: "诊断",
    refreshing: "刷新中...",
    refresh: "刷新",
    updated: `更新于 \${time}`,
  },

  // Appearance Settings
  appearance: {
    theme: "主题",
    light: "浅色",
    dark: "深色",
    zinc: "锌色",
    midnight: "午夜",
    claude: "Claude",
    ghostty: "Ghostty",
    system: "跟随系统",
    fonts: "字体",
    interfaceFont: "界面字体",
    interfaceFontHint: "整个应用使用。留空则使用系统默认",
    systemDefault: "系统默认",
    interfaceSize: "界面大小",
    px: "像素",
    codeFont: "代码字体",
    codeFontHint: "在代码、差异和终端输出中使用。留空则使用系统默认",
    codeSize: "代码大小",
    syntax: "语法",
    highlightTheme: "高亮主题",
    highlightThemeHint: "代码颜色，独立于应用主题",
  },

  // Keyboard Shortcuts
  shortcuts: {
    pressShortcut: "按下快捷键...",
    done: "完成",
    cancel: "取消",
    rebind: "重新绑定",
    reset: "重置",
    resetAll: "全部重置",
    desktopOnly: "键盘快捷键仅在桌面端可用",
    openProject: "打开项目",
    newWorktree: "新建工作树",
    archiveWorktree: "归档工作树",
    newTab: "新建标签页",
    closeTab: "关闭当前标签页",
    jumpToWorkspace: "跳转到工作区",
    jumpToTab: "跳转到标签页",
    prevWorkspace: "上一个工作区",
    nextWorkspace: "下一个工作区",
    prevTab: "上一个标签页",
    nextTab: "下一个标签页",
    toggleSidebar: "切换侧边栏",
    toggleFocusMode: "切换专注模式",
    settings: "设置",
    commandCenter: "命令中心",
    toggleSourceControl: "切换源代码控制",
    toggleFileExplorer: "切换文件浏览器",
    toggleTerminal: "切换终端",
    toggleAgentList: "切换代理列表",
  },

  // Workspace Screen
  workspace: {
    newAgent: "新建代理",
    setup: "设置",
    terminal: "终端",
    browser: "浏览器",
    agent: "代理",
    workspaceSetup: "工作区设置",
    loading: "加载中...",
    workspace: "工作区",
    switchTab: "切换标签页",
    searchTabs: "搜索标签页",
    workspaceActions: "工作区操作",
    newAgentAction: "新建代理",
    newTerminal: "新建终端",
    newBrowserTab: "新建浏览器标签页",
    importSession: "导入会话",
    copyWorkspacePath: "复制工作区路径",
    copyBranchName: "复制分支名称",
    showSetup: "显示设置",
    missingDir: "工作区执行目录缺失。请在打开标签页前重新加载工作区数据。",
    noTabs: "暂无标签页。使用新建标签页创建代理或终端。",
    pathNotAvailable: "工作区路径暂不可用",
    preparing: "正在准备工作区，准备就绪后打开终端...",
    agentId: "代理 ID",
    copyFailed: "复制失败",
    resumeIdNotAvailable: "恢复 ID 不可用",
    resumeCommandNotAvailable: "恢复命令不可用",
    resumeCommand: "恢复命令",
    hostNotConnected: "主机未连接",
    reloadingAgent: "正在重新加载代理...",
    reloadedAgent: "已重新加载代理",
    failedToReload: "重新加载代理失败",
    workspacePathNotAvailable: "工作区路径不可用",
    workspacePath: "工作区路径",
    branchNameNotAvailable: "分支名称不可用",
    branchName: "分支名称",
    closeTerminal: "关闭终端？",
    archiveRunningAgent: "归档运行中的代理？",
    closeLeft: "关闭左侧标签页？",
    closeRight: "关闭右侧标签页？",
    closeOther: "关闭其他标签页？",
    copyResumeCommand: "复制恢复命令",
    copyAgentId: "复制代理 ID",
    rename: "重命名",
    closeAbove: "关闭上方标签页",
    closeToLeft: "关闭左侧标签页",
    closeBelow: "关闭下方标签页",
    closeToRight: "关闭右侧标签页",
    closeOthers: "关闭其他标签页",
    reloadAgent: "重新加载代理",
    reloadAgentHint: "重新加载代理以更新技能、MCP 或登录状态。",
    close: "关闭",
    bulkCloseConfirm: `这将归档 \${n} 个代理、关闭 \${n} 个终端和 \${n} 个标签页。已关闭终端中运行的进程将立即停止。`,
    noTabsInPane: "此面板中没有标签页。",
    toggleExplorer: "切换资源管理器",
    connecting: "连接中",
    isOffline: `\${name} 已离线`,
    cannotReach: `无法连接到 \${name}`,
    loadingWorkspace: "加载工作区中",
    hostStatus: `主机状态: \${status}`,
    retry: "重试",
    manageHost: "管理主机",
    workspaceNotFound: "未找到工作区",
  },

  // Branch Switcher
  branch: {
    switchBranch: "切换分支...",
    filterBranches: "筛选分支...",
    noBranches: "未找到分支。",
    switchTitle: "切换分支",
    currentBranch: `当前分支: \${name}。按以切换分支。`,
    restoreStashed: "恢复暂存的更改？",
    restoreStashedMsg: "此分支有来自上次会话的暂存更改。是否要恢复它们？",
    restore: "恢复",
    later: "稍后",
    stashedRestored: "已恢复暂存的更改",
    uncommittedChanges: "未提交的更改",
    uncommittedChangesMsg: "您有未提交的更改。切换分支前是否暂存它们？",
    stashAndSwitch: "暂存并切换",
    failedToStash: "暂存更改失败",
    failedToSwitch: "切换分支失败",
  },

  // Command Center
  commandCenter: {
    placeholder: "输入命令或搜索代理...",
    noMatches: "无匹配项",
    actions: "操作",
    agents: "代理",
    newAgent: "新建代理",
    openProject: "打开项目",
    home: "主页",
    settings: "设置",
  },

  // New Workspace Screen
  newWorkspace: {
    title: "新建工作区",
    create: "创建",
    startFrom: "从...开始",
    searchPlaceholder: "搜索分支和 PR",
    chooseWhere: "选择从哪里开始",
    checkoutPR: `检出 PR #\${number}？`,
    searching: "搜索中...",
    noMatchingRefs: "无匹配的引用。",
    selectModel: "请选择模型",
    composerRequired: "需要编辑器状态",
  },

  // Project Settings
  projectSettings: {
    backToProjects: "返回项目",
    agentTitles: "代理标题",
    agentTitlesHint: "保持标题为祈使句且不超过 40 个字符",
    branchNames: "分支名称",
    branchNamesHint: "分支使用 feat/ 或 fix/ 前缀，个人分支使用 mb/",
    commitMessages: "提交消息",
    commitMessagesHint: "使用带有范围的常规提交",
    pullRequests: "拉取请求",
    pullRequestsHint: "以一段摘要开头，包含测试计划部分",
    noEditableCopy: "我们在任何已连接的主机上都没有此项目的可编辑副本。",
    hostDoesntHave: "此主机没有此项目",
    switchOrReload: "切换到上方的其他主机，或重新加载。",
    noRecord: "所选主机没有此项目的记录。",
    couldntLoad: "无法加载 paseo.json",
    hostDidntRespond: "主机未响应。",
    reloadToTry: "重新加载以重试。",
    couldntParse: "无法解析 paseo.json",
    fixAndReload: "修复磁盘上的文件，然后重新加载。",
    reload: "重新加载",
    switchHost: "切换主机",
    worktreeHooks: "工作树生命周期钩子",
    worktreeHooksHint: "为此项目创建或拆除工作树时运行的命令",
    setup: "设置",
    setupPlaceholder: "npm install",
    teardown: "拆除",
    teardownPlaceholder: "docker compose down",
    docs: "文档",
    scripts: "脚本",
    scriptsHint: "可从此项目中的任何代理启动的长期运行服务和一次性命令",
    noScripts: "暂无脚本。",
    untitledScript: "未命名脚本",
    nameRequired: "名称为必填项",
    commandRequired: "命令为必填项",
    removeScript: "移除脚本？",
    removeScriptConfirm: `确定要移除 \${name} 吗？`,
    metadataGeneration: "元数据生成",
    metadataHint: "注入到 AI 提示中的项目特定指令...",
    configChanged: "磁盘上的配置已更改",
    reloadBeforeSave: "保存前重新加载以获取最新的 paseo.json。",
    couldntSave: "无法保存 paseo.json",
    tryAgainOrReload: "重试，或从磁盘重新加载最新版本。",
    tryAgain: "重试",
    saving: "保存中...",
    save: "保存",
    projectSaved: "项目已保存",
    projectRenamed: "项目已重命名",
    couldntRename: "无法重命名项目",
    newScript: "新建脚本",
    editScript: `编辑 \${name}`,
    name: "名称",
    namePlaceholder: "dev",
    command: "命令",
    commandPlaceholder: "npm run dev",
    runAsService: "作为服务运行",
    runAsServiceHint: "Paseo 监督进程并通过 $PASEO_PORT 分配端口",
    edit: "编辑",
    remove: "移除",
    reset: "重置",
    version: "版本",
    versionHint: "此项目要求的最低 Paseo 版本",
    view: "查看",
  },

  // Open Project / Home Screen
  home: {
    addProject: "添加项目",
    addProjectDesc: "打开您机器上的文件夹",
    importSession: "导入会话",
    importSessionDesc: "引入最近的外部 CLI 会话",
    setupProviders: "设置提供商",
    setupProvidersDesc: "配置 Claude Code、Codex 等",
    pairDevice: "配对设备",
    pairDeviceDesc: "将手机连接到此守护进程",
  },

  // Sessions Screen
  sessions: {
    title: "会话",
    noSessions: "暂无会话",
    back: "返回",
    loading: "加载中...",
    loadMore: "加载更多",
  },

  // Projects Screen
  projects: {
    noProjects: "暂无项目",
    couldntLoad: `无法从主机 \${name} 加载项目: \${message}`,
  },

  // Startup / Error Screen
  startup: {
    somethingWentWrong: "出了点问题",
    errorMsg: "本地服务器启动失败。如果此问题持续发生，请在 GitHub 上报告问题并包含以下日志。",
    loadingLogs: "加载守护进程日志中...",
    noLogs: "无守护进程日志可用。",
    unableToLoadLogs: `无法加载守护进程日志: \${message}`,
    copyLogs: "复制日志",
    openGitHubIssue: "打开 GitHub Issue",
    docs: "文档",
    retry: "重试",
  },

  // Quitting Overlay
  quitting: {
    title: "正在退出 Paseo...",
    detail: "正在停止本地守护进程。",
  },

  // Community Links
  community: {
    star: "Star",
    sponsor: "赞助",
    community: "社区",
  },

  // Import Session Sheet
  importSession: {
    title: "导入会话",
    all: "全部",
    connectToImport: "连接到主机以导入会话",
    updateHost: "更新主机以导入会话。",
    noProviders: "未启用可导入的提供商。",
    loadingRecent: "加载最近的会话中...",
    couldntLoad: "无法加载最近的会话。",
    couldntLoadFor: `无法加载 \${names} 的会话。`,
    couldntImport: "无法导入选中的会话。",
    importing: "导入中...",
    refreshSessions: "刷新会话",
    missingWorkingDir: "会话缺少工作目录",
  },

  // Rename Modal
  rename: {
    title: "重命名",
    cancel: "取消",
    saving: "保存中...",
    nameRequired: "名称为必填项",
    unableToSave: "无法保存",
  },

  // Confirm Dialog
  confirm: {
    confirm: "确认",
    cancel: "取消",
  },

  // Toast Messages
  toast: {
    reconnecting: "重新连接中...",
    couldntLoadHistory: "无法加载更早的历史记录",
    failedToStart: `启动 \${scriptName} 失败`,
    failedToOpen: "打开工作区失败",
    pathCopied: "路径已复制",
    branchNameCopied: "分支名称已复制",
    failedToRemove: "移除工作区失败",
    failedToArchive: "归档工作树失败",
    failedToHide: "隐藏工作区失败",
    failedToRename: "重命名分支失败",
    removeProject: "移除项目？",
  },

  // Voice Overlay
  voice: {
    unmute: "取消静音实时语音",
    mute: "静音实时语音",
    stop: "停止实时语音并中断回合",
  },

  // Composer
  composer: {
    placeholder: "发送消息给代理，使用 @file 标记文件，或使用 /命令",
    placeholderAlt: "消息，@文件，/命令",
    addAttachment: "添加附件",
    interruptAgent: "中断代理",
    queueMessage: "排队消息",
    sendAndInterrupt: "发送并中断",
    sendMessage: "发送消息",
    unmuteVoice: "取消静音语音模式",
    muteVoice: "静音语音模式",
    stopDictation: "停止听写",
    startDictation: "开始听写",
    queue: "排队",
    send: "发送",
    addImage: "添加图片",
    addIssueOrPR: "添加 Issue 或 PR",
    searching: "搜索中...",
    noResults: "未找到结果",
    searchIssues: "搜索 Issue 和 PR...",
    attachIssueOrPR: "附带 Issue 或 PR",
    failedToSend: "发送消息失败",
    enableVoice: "启用语音模式",
    disableVoice: "禁用语音模式",
    editQueued: "编辑排队消息",
    sendQueued: "立即发送排队消息",
    openImage: "打开图片附件",
    removeImage: "移除图片附件",
    cancelAgent: "取消代理",
    stopAgent: "停止代理",
    noPreview: "无预览",
    noRecentSessions: "无最近会话可导入。",
  },

  // Agent Controls
  agentControls: {
    provider: "提供商",
    unknown: "未知",
    selectProvider: "选择代理提供商",
    selectThinking: "选择思考选项",
    openFeatures: "打开代理功能",
    thinking: "思考",
    on: "开",
    off: "关",
    features: "功能",
    mode: "模式",
    searchModes: "搜索模式...",
    selectMode: "选择模式",
    failedToSave: "保存模型失败",
    addCustomModel: "添加自定义模型",
    modelId: "模型 ID",
    modelIdPlaceholder: "例如 openai/gpt-5",
    failedToFetch: "获取诊断信息失败",
    addCustom: "添加",
    adding: "添加中...",
    noModels: "未找到匹配的模型",
    noDetected: "未检测到模型",
    discovered: "已发现",
    customModels: "自定义模型",
    loadingSelector: "加载模型选择器中...",
    loadingModels: "加载模型中...",
    noMatchSearch: "无匹配的模型",
    favorite: "收藏夹",
    run: "运行",
    view: "查看",
  },

  // File Explorer
  fileExplorer: {
    workspaceUnavailable: "工作区不可用",
    back: "返回",
    retry: "重试",
    loadingFiles: "加载文件中...",
    noFiles: "无文件",
    loadingFile: "加载文件中...",
    noPreview: "无可用预览",
    binaryPreview: "二进制文件无法预览",
    failedToLoad: "加载文件失败",
    dropImages: "拖放图片到此处",
  },

  // Agent List
  agentList: {
    hostOffline: "主机离线",
    archiveWarning: "此代理仍在运行。归档将停止代理。",
    cancel: "取消",
    archive: "归档",
  },

  // Project Picker
  projectPicker: {
    typePath: "输入目录路径...",
    opening: "正在打开项目...",
    startTyping: "开始输入路径",
  },

  // Tool Call Details
  toolCallDetails: {
    input: "输入",
    output: "输出",
    error: "错误",
    noDetails: "无可用详细信息",
  },

  // Rewind
  rewind: {
    rewindTo: "回退到此消息",
    cannotUndo: "此操作无法撤销",
  },

  // Question Form
  questionForm: {
    dismissed: "已被用户忽略",
    submit: "提交",
  },

  // Attachment Lightbox
  attachmentLightbox: {
    dismiss: "关闭图片",
    loadFailed: "无法加载图片",
    close: "关闭图片",
  },

  // Archived Agent
  archivedAgent: {
    archived: "此代理已归档",
    unarchive: "取消归档",
  },

  // Download Toast
  download: {
    starting: "开始下载...",
    complete: "下载完成",
    failed: "下载失败",
  },

  // Context Window
  contextWindow: {
    title: "上下文窗口",
    used: `\${percentage}% 已使用`,
    tokens: `\${used} / \${max} 个 token`,
    cost: `会话费用 \${cost}`,
  },

  // Browser
  browser: {
    desktopOnly: "浏览器仅在桌面端可用",
    openInElectron: "在 Electron 中打开此工作区以使用内置浏览器。",
    session: `浏览器会话 \${id}`,
    failedToLoad: "加载页面失败",
    enterUrl: "输入 URL",
    cancelSelect: "取消元素选择",
    selectElement: "选择元素",
  },

  // Workspace Scripts
  workspaceScripts: {
    scripts: "脚本",
    run: "运行",
    view: "查看",
  },

  // Sidebar
  sidebar: {
    addProject: "添加项目",
    home: "主页",
    settings: "设置",
    switchHost: "切换主机",
    closeSidebar: "关闭侧边栏",
    workspaceActions: "工作区操作",
    projectActions: "项目操作",
    creating: "创建中...",
    newWorkspace: "新建工作区",
    noProjects: "暂无项目",
    addProjectHint: "添加项目开始使用",
  },

  // Worktree Setup
  worktreeSetup: {
    title: "设置工作树脚本",
    description: "添加设置命令，以便新工作树可以自动安装依赖并自行准备。",
    openSettings: "打开项目设置",
  },

  // Common
  common: {
    search: "搜索...",
    noOptions: "无匹配选项。",
    select: "选择",
    loading: "加载中...",
    noResults: "未找到结果",
    error: `错误: \${msg}`,
    confirm: "确认",
    cancel: "取消",
    save: "保存",
    saving: "保存中...",
    reset: "重置",
    retry: "重试",
    close: "关闭",
    remove: "移除",
    edit: "编辑",
    done: "完成",
    nameRequired: "名称为必填项",
    unableToSave: "无法保存",
  },
};

export type StringKeys = typeof strings;
